language: go
go:
- 1.x
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y wget bzip2
# install GMP 6.1.0
- sudo wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2
- sudo bunzip2 gmp-6.1.2.tar.bz2
- sudo tar xvf gmp-6.1.2.tar
- cd gmp-6.1.2
- sudo ./configure
- sudo make && sudo make check && sudo make install
# install MPFR
- sudo wget http://www.mpfr.org/mpfr-current/mpfr-4.0.1.tar.bz2
- sudo bunzip2 mpfr-4.0.1.tar.bz2
- sudo tar xvf mpfr-4.0.1.tar
- cd mpfr-4.0.1
- curl http://www.mpfr.org/mpfr-4.0.1/allpatches | patch -N -Z -p1
- sudo ./configure
- sudo make -C deps distclean-gmp
- sudo make check && sudo make install
# install FLINT
- sudo wget http://www.flintlib.org/flint-2.5.2.tar.gz
- sudo tar xzf flint-2.5.2.tar.gz
- cd flint-2.5.2
- sudo ./configure
- sudo make && sudo make check && sudo make install
install:
- go get -t ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- make test
after_success:
- $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
notifications:
  email: false
