language: go
go:
- 1.x
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libgmp3-dev
- sudo apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg
install:
- go get -t ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- make test
after_success:
- $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
notifications:
  email: false
