Simulation = "Aggregation"
Servers = 5
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = "24h"
Bandwidth = 1000
TAGS = "vartime"

Hosts, DpsPerServerTimesDPNbrOutput, NbrDPsTotal, Proofs
5, 1, 5, true
5, 14, 5, true
5, 2, 10, true
5, 28, 10, true
5, 3, 15, true
5, 42, 15, true
5, 5, 25, true
5, 70, 25, true
5, 10, 50, true
5, 140, 50, true
5, 20, 100, true
5, 280, 100, true
5, 50, 250, true
5, 700, 250, true
5, 100, 500, true
5, 1400, 500, true
5, 200, 1000, true
5, 2800, 1000, true