Simulation = "Verification"
Servers = 5
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = "24h"
Bandwidth = 1000
TAGS = "vartime"

Hosts, NbrDPsTotal, OperationInt, Proofs
5,  10, 0, true
5,  10, 1, true
5,  10, 3, true
5,  10, 2, true
5,  10, 5, true
5,  10, 4, true