Simulation = "Aggregation"
Servers = 5
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = "24h"
Bandwidth = 1000
TAGS = "vartime"

Hosts, DpsPerServerTimesDPNbrOutput, NbrDPsTotal, Proofs
5, 2, 10, true
5, 6, 10, true
5, 200, 10, true
5, 28, 10, true