Simulation = "Aggregation"
Servers = 13
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = "24h"
Bandwidth = 100
TAGS = "vartime"
Delay = 20

Hosts, DpsPerServerTimesDPNbrOutput, NbrDPsTotal, Proofs
12, 30, 120, true
12, 1000, 120, true
12, 300, 1200, true
12, 10000, 1200, true