Simulation = "Aggregation"
Servers = 6
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = "24h"
Bandwidth = 100
TAGS = "vartime"
Delay = 20

Hosts, DpsPerServerTimesDPNbrOutput, NbrDPsTotal, Proofs
6, 30, 60, true
6, 1000, 60, true
6, 300, 600, true
6, 10000, 600, true